openapi: 3.0.0
info:
  title: API Gateway Service
  description: API Gateway
  version: 0.1.9
servers:
  - url: /api
tags:
  - Auth
  - Users
  - Tweets
paths:
  /auth/register:
    $ref: './auth/paths.yaml#/Register'
  /auth/login:
    $ref: './auth/paths.yaml#/Login'
  /auth/logout:
    $ref: './auth/paths.yaml#/Logout'
  /auth/current:
    $ref: './auth/paths.yaml#/Current'

  /accounts/search:
    $ref: './accounts/paths.yaml#/SearchAccounts'
  /account:
    $ref: './accounts/paths.yaml#/CurrentAccount'
  /accounts/{username}:
    $ref: './accounts/paths.yaml#/AccountByUsername'
  /account/followers:
    $ref: './accounts/paths.yaml#/AccountFollowers'
  /account/following:
    $ref: './accounts/paths.yaml#/AccountFollowing'
  /account/follow:
    $ref: './accounts/paths.yaml#/FollowAccount'
  /account/unfollow:
    $ref: './accounts/paths.yaml#/UnfollowAccount'

  /tweets/search:
    $ref: './tweets/paths.yaml#/SearchTweets'
  /tweets:
    $ref: './tweets/paths.yaml#/CreateTweet'
  /tweets/{id}:
    $ref: './tweets/paths.yaml#/CurrentTweet'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    PathId:
      in: path
      name: id
      required: true
      schema:
        type: integer
        minimum: 1
      description: Числовой id
      example: 1
    QueryInclude:
      in: query
      name: include
      required: false
      description: Relationships
      schema:
        type: string
  schemas:
    EmptyResource:
      type: object
      properties:
        data:
          type: object
          nullable: true
          example: null
    SearchResourceRequest:
      type: object
      properties:
        filter:
          type: object
          properties:
            name:
              type: string
        include:
          type: array
        sort:
          type: array
