services:
  nginx:
    image: nginx:alpine
    ports:
      - ${NGINX_PORT:-8080}:80
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
  app:
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - ${APP_PORT:-9001}:900
      - ${VITE_PORT:-5173}:5173
    working_dir: /var/www
